baseURL = 'https://zhaoyoubo.github.io/TechBlog/'
languageCode = 'en-us'
title = '赵容博的博客'
theme = 'FixIt'
defaultContentLanguage = 'zh-cn'
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"